---
- name: Show cloud_dns_zones
  ansible.builtin.debug:
    var: cloud_dns_zones

- name: Setup DNS
  ansible.builtin.include_tasks: "{{ zone.provider }}-zone.yaml"
  with_items: "{{ cloud_dns_zones }}"
  loop_control:
    loop_var: zone
